apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    app: candidate-finder
data:
  BEDROCK_REGION: "us-east-1"
  BEDROCK_COMPLETION_MODEL_ID: "anthropic.claude-3-sonnet-20240229-v1:0"
  BEDROCK_EMBEDDING_MODEL_ID: "amazon.titan-embed-text-v1"
  CHROMA_PERSIST_DIR: "/app/chroma_db"
  DATABASE_URL: "sqlite+aiosqlite:////app/db/phase1.db"
  DEBUG: "true"
