apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-assistant-sa
  namespace: default
  labels:
    app: candidate-finder
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-assistant-role
rules:
# Allow reading pods, services, deployments, etc. (read-only operations)
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "persistentvolumeclaims", "nodes", "namespaces"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch"]
# Allow reading logs
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-assistant-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-assistant-role
subjects:
- kind: ServiceAccount
  name: k8s-assistant-sa
  namespace: default
